name: Build and Test

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install --fix-missing libgl1-mesa-dev libglfw3 libglfw3-dev wget curl -y

      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..

      - name: Set up Tests
        run: |
          cd tests
          bash ./download_test.sh
          cd ..

      - name: Run tests
        run: |
          cd build
          ./gb_test --gtest_output=json || echo "Done!"
          cd ..

      - name: Generate test report
        run: |
          echo "Generating test report..."
          python3 ./tests/generate_test_report.py ${{ github.sha }} ./build/test_detail.json > ./build/README.md
          git fetch --all
          git checkout test_report
          mv ./build/README.md ./

      - name: Push test report to branch test_report
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ github.sha }} test report
          branch: test_report
          repository: .
          skip_dirty_check: true
          skip_fetch: true
          file_pattern: 'README.md'
